#!/bin/bash

Person1=Hareesh# no space before and after equal
Person2=Vannela

echo "$Person1:: Hi $Person2"
echo "$Person2:: Hello $Person1"
echo "$Person1:: How are you:"
echo "$Person2:: I am good. how are you?"